server:
  port: 7000

spring:
  application:
    name: ms-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/VederQC/CanchasExamen-main.git
          searchPaths:
            - config-data
          default-label: canchas

  security:
    user:
      name: root
      password: 123456
